#pragma once

#include "ECS/Components/TransformComponent.hpp"
#include "ECS/Components/CameraComponent.hpp"
#include "ECS/Components/MeshRendererComponent.hpp"
#include "ECS/Components/DirectionalLightComponent.hpp"
#include "ECS/Components/PointLightComponent.hpp"
#include "ECS/Components/SpotLightComponent.hpp"
#include "ECS/Components/AudioSourceComponent.hpp"
#include "ECS/Components/AudioListenerComponent.hpp"
#include "ECS/Components/IRigidbodyComponent.hpp"
#include "ECS/Components/BoxRigidbodyComponent.hpp"
#include "ECS/Components/CapsuleRigidbodyComponent.hpp"
#include "ECS/Components/SphereRigidbodyComponent.hpp"
#include "ECS/Components/TextRendererComponent.hpp"
#include "ECS/Components/CppScriptComponent.hpp"